# Generated by Django 4.2.5 on 2023-09-06 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('house', models.PositiveSmallIntegerField()),
                ('open', models.TimeField()),
                ('close', models.TimeField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.city')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.street')),
            ],
        ),
    ]
