# Generated by Django 4.2.5 on 2023-09-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
