# Generated by Django 4.2.5 on 2023-09-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_is_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='is_open',
        ),
        migrations.AddField(
            model_name='shop',
            name='close_uts',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='open_utc',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
