# Generated by Django 4.2.5 on 2023-09-07 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_alter_city_options_alter_street_options_and_more'),
        ('shops', '0003_remove_shop_is_open_shop_close_uts_shop_open_utc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AlterField(
            model_name='shop',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='close',
            field=models.TimeField(verbose_name='Время закрытия'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='house',
            field=models.PositiveSmallIntegerField(verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название магазина'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='open',
            field=models.TimeField(verbose_name='Время открытия'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.street', verbose_name='Улица'),
        ),
    ]
